/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CorporateRouteImport } from './routes/corporate'
import { Route as HeritageRouteImport } from './routes/heritage'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OccasionsRouteImport } from './routes/occasions'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateRoute = CorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => rootRouteImport,
} as any)
const HeritageRoute = HeritageRouteImport.update({
  id: '/heritage',
  path: '/heritage',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OccasionsRoute = OccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/occasions': typeof OccasionsRoute
  '/shop': typeof ShopRoute
  '/store-locator': typeof StoreLocatorRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/occasions': typeof OccasionsRoute
  '/shop': typeof ShopRoute
  '/store-locator': typeof StoreLocatorRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/corporate': typeof CorporateRoute
  '/heritage': typeof HeritageRoute
  '/journal': typeof JournalRoute
  '/occasions': typeof OccasionsRoute
  '/shop': typeof ShopRoute
  '/store-locator': typeof StoreLocatorRoute
  '/products/$slug': typeof ProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/corporate'
    | '/heritage'
    | '/journal'
    | '/occasions'
    | '/shop'
    | '/store-locator'
    | '/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/corporate'
    | '/heritage'
    | '/journal'
    | '/occasions'
    | '/shop'
    | '/store-locator'
    | '/products/$slug'
  id:
    | '__root__'
    | '/'
    | '/corporate'
    | '/heritage'
    | '/journal'
    | '/occasions'
    | '/shop'
    | '/store-locator'
    | '/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CorporateRoute: typeof CorporateRoute
  HeritageRoute: typeof HeritageRoute
  JournalRoute: typeof JournalRoute
  OccasionsRoute: typeof OccasionsRoute
  ShopRoute: typeof ShopRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate': {
      id: '/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof CorporateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/heritage': {
      id: '/heritage'
      path: '/heritage'
      fullPath: '/heritage'
      preLoaderRoute: typeof HeritageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/occasions': {
      id: '/occasions'
      path: '/occasions'
      fullPath: '/occasions'
      preLoaderRoute: typeof OccasionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CorporateRoute: CorporateRoute,
  HeritageRoute: HeritageRoute,
  JournalRoute: JournalRoute,
  OccasionsRoute: OccasionsRoute,
  ShopRoute: ShopRoute,
  StoreLocatorRoute: StoreLocatorRoute,
  ProductsSlugRoute: ProductsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
